### ISSUE TITLE
Add `string.contains`

### ISSUE THREAD

**Issue by Panquesito7** [joseliojunior/lua-extensions#1]
### Description

It'd be great if a `string.contains` function could be added.
This can be very useful in a lot of ways when checking if a string has a certain substring.

This is a very simple code that works, however, it could be improved.

```lua
--- @brief Checks if the given string
--- contains a certain substring.
--- @param str the string to check
--- @param substr the substring to check for
--- @returns true if `substr` was found in `str`
--- @returns false if `substr` was NOT found in `str`
function string.contains(str, substr)
    local substr_length = #substr
    for i = 1, #str do
        if str:sub(i, i + substr_length - 1) == substr then
            return true
        end
    end

    return false
end
```

**Comment by lunatic-fox** [comment]
Thank you for your input to this project! 🚀
I'll add it and the credits when I have more time to review the project code.

> I was working on `string:split.map()` and `string:split.join()`. And they are showing great results. 🤩

**Comment by lunatic-fox** [comment]
Done at afe9856eb84ccb79eef5b1ce41e7f2412856c5ed! 🚀
